### ISSUE TITLE
Military format doesn't support specifying a date

### ISSUE THREAD

**Issue by chadfawcett** [tickbin/parser#27]
If I try and specify a date before the military time, it thinks there is no time.

<img width="575" alt="screen shot 2016-08-11 at 8 52 06 pm" src="https://cloud.githubusercontent.com/assets/3250463/17612343/a3b2e670-6005-11e6-98d1-6e1d23fca970.png">

**Comment by jonotron** [comment]
This is probably thinking the time is a year.

What should we do if someone specifies Aug 11 2015-2100 ?? How do we even parse that.

I suspect we need to remove support for time with no delimiter.

**Comment by chadfawcett** [comment]
Ah right! Good catch.

**Comment by chrisfosterelli** [comment]
@jonotron What do you mean time with no delimiter? You mean the ":" character?

**Comment by jonotron** [comment]
Ya, times like `2015` are ambiguous... hard to know if the year is intended or 8:15pm. Possibly we drop support for military time? Or should refine?

**Comment by chrisfosterelli** [comment]
Isn't it unambiguous as long as it is displayed in a range? It may be harder to parse intelligently, but I don't think impossible.

For example: `Aug 11 2015-2100`, it has to be 8:15pm because otherwise it's an invalid entry anyway.

Although you're right it may be easier to just require the colon, since that's not an actual standard of 24 time just a habit of military from what I understand anyway.
