### ISSUE TITLE
Date not removed from duration message

### ISSUE THREAD

**Issue by chadfawcett** [tickbin/parser#35]
Date and time references are supposed to be removed from the display message. Here, 'yesterday' is still left in the message.

original commit message was `tick commit "yesterday 7.5 hours #stat #robot"`

![screen shot 2016-10-14 at 12 16 23 pm](https://cloud.githubusercontent.com/assets/3250463/19399828/3d505b9e-9208-11e6-9b1f-894c30eef9e7.png)

**Comment by chadfawcett** [comment]
We may need an upgrade script to go back and change what is stored on the entry document/

**Comment by jonotron** [comment]
This is limited to duration parsing only, works as expected with times are provided: 
![tickbin 2016-10-14 12-58-34](https://cloud.githubusercontent.com/assets/349600/19401055/f4187794-920d-11e6-9ceb-dc29be68a774.jpg)

**Comment by mccullochk** [comment]
After briefly looking at this (and with my limited knowledge about the inner workings of tickbin) it seems like this may an issue with `chrono-node`.

`chrono.parse(str)` returns the expected output with "Yesterday 4 hours" (no decimal) and "4.5 hours Yesterday" (Yesterday after hours) but not "Yesterday 4.5 hours".

**Comment by chadfawcett** [comment]
@mccullochk Can you look into reporting this upstream then? Or checking to see if has been reported? 

In the meantime there is the option of writing a `refiner` (`src/refiners`) or `helper` (`src/helpers`) that fixes this for us.

**Comment by mccullochk** [comment]
@chadfawcett, I updated `chrono-node` to it's latest release just to make sure it hasn't already been solved in a new release (it hasn't) and looked at all the existing issues. It doesn't look like it has been reported yet. However, I'm a little uneasy about reporting it since I don't think I can explain exactly what the problem is / don't fully understand myself what the problem is.

I have played around with creating a small `refiner` and have got something working but again until I feel like I have a better understanding of exactly what the issue is I'm not super confident my implementation is sufficient.
